# Generated by Django 3.2.5 on 2021-10-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='userID',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='openid',
            field=models.CharField(default='', max_length=28, verbose_name='微信openid'),
        ),
    ]
