# Generated by Django 3.2.5 on 2021-10-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_auto_20211004_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='phonenumber',
            new_name='phoneNumber',
        ),
    ]
