# Generated by Django 3.2.8 on 2021-10-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0003_rename_phonenumber_usermodel_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='avatar',
            field=models.URLField(default='http://dummyimage.com/300x300', verbose_name='头像'),
        ),
    ]
